version: "3"
services:
    mysql:
      image: mysql:latest
      container_name: mysql-container
      ports:
        - 3306:3306
      volumes:
        - ./db/setup.sql:/docker-entrypoint-initdb.d/dump.sql
      environment:
        MYSQL_ROOT_PASSWORD: <PASSWORD>
        MYSQL_DATABASE: walpp
    application:
      build: .
      container_name: walpp
      ports:
        - "8080:8080"
      depends_on:
        - mysql
